var data = ["год","человек","время","дело","жизнь","день","рука","раз","работа","слово","место","лицо","друг","глаз","вопрос","дом","сторона","страна","мир","случай","голова","ребенок","сила","конец","вид","система","часть","город","отношение","женщина","деньги","земля","машина","вода","отец","проблема","час","право","нога","решение","дверь","образ","история","власть","закон","война","бог","голос","тысяча","книга","возможность","результат","ночь","стол","имя","область","статья","число","компания","народ","жена","группа","развитие","процесс","суд","условие","средство","начало","свет","пора","путь","душа","уровень","форма","связь","минута","улица","вечер","качество","мысль","дорога","мать","действие","месяц","государство","язык","любовь","взгляд","мама","век","школа","цель","общество","деятельность","организация","президент","комната","порядок","момент","театр","письмо","утро","помощь","ситуация","роль","рубль","смысл","состояние","квартира","орган","внимание","тело","труд","сын","мера","смерть","рынок","программа","задача","предприятие","окно","разговор","правительство","семья","производство","информация","положение","центр","ответ","муж","автор","стена","интерес","федерация","правило","управление","мужчина","идея","партия","совет","счет","сердце","движение","вещь","материал","неделя","чувство","глава","наука","ряд","газета","причина","плечо","цена","план","речь","точка","основа","товарищ","культура","данные","мнение","документ","институт","ход","проект","встреча","директор","срок","палец","опыт","служба","судьба","девушка","очередь","лес","состав","член","количество","событие","объект","зал","создание","значение","период","шаг","брат","искусство","структура","номер","пример","исследование","гражданин","игра","начальник","рост","тема","принцип","метод","тип","фильм","край","гость","воздух","характер","борьба","использование","размер","образование","мальчик","кровь","район","небо","армия","класс","представитель","участие","девочка","политика","герой","картина","доллар","спина","территория","пол","поле","изменение","направление","рисунок","течение","церковь","банк","сцена","население","большинство","музыка","правда","свобода","память","команда","союз","врач","договор","дерево","факт","хозяин","природа","угол","телефон","позиция","двор","писатель","самолет","объем","род","солнце","вера","берег","спектакль","фирма","способ","завод","цвет","журнал","руководитель","специалист","оценка","регион","песня","процент","родитель","море","требование","основание","половина","роман","круг","анализ","стихи","автомобиль","экономика","литература","бумага","поэт","степень","господин","надежда","предмет","вариант","министр","граница","дух","модель","операция","пара","сон","название","ум","повод","старик","миллион","успех","счастье","ребята","кабинет","магазин","пространство","выход","удар","база","знание","текст","защита","руководство","площадь","сознание","возраст","участник","участок","пункт","линия","желание","папа","доктор","губа","дочь","среда","председатель","представление","солдат","художник","волос","оружие","соответствие","ветер","парень","зрение","генерал","огонь","понятие","строительство","ухо","грудь","нос","страх","услуга","содержание","радость","безопасность","продукт","комплекс","бизнес","сад","сотрудник","лето","курс","предложение","рот","технология","реформа","отсутствие","собака","камень","будущее","рассказ","контроль","река","продукция","сумма","техника","здание","сфера","необходимость","фонд","подготовка","лист","республика","хозяйство","воля","бюджет","снег","деревня","мужик","элемент","обстоятельство","немец","победа","источник","звезда","выбор","масса","итог","сестра","практика","проведение","карман","слава","кухня","определение","функция","войско","комиссия","применение","капитан","работник","обеспечение","офицер","фамилия","предел","выборы","ученый","бутылка","бой","теория","зона","отдел","зуб","разработка","личность","гора","товар","метр","праздник","влияние","читатель","удовольствие","актер","слеза","ответственность","учитель","акт","боль","множество","особенность","показатель","корабль","звук","впечатление","частность","детство","вывод","профессор","доля","норма","прошлое","командир","коридор","поддержка","рамка","враг","этап","черт","дед","собрание","прием","болезнь","клетка","кожа","заявление","попытка","сравнение","расчет","депутат","комитет","знак","дядя","учет","хлеб","чай","режим","целое","вирус","выражение","здоровье","зима","десяток","глубина","сеть","студент","секунда","скорость","поиск","суть","налог","ошибка","доход","режиссер","поверхность","ощущение","карта","клуб","станция","революция","колено","министерство","стекло","этаж","высота","бабушка","трубка","газ","мастер","поведение","столица","механизм","передача","способность","подход","энергия","существование","исполнение","кино","сожаление","заместитель","ресурс","акция","рождение","администрация","стоимость","улыбка","артист","сосед","фраза","фигура","субъект","реакция","список","фотография","журналист","май","нарушение","заседание","толпа","больница","существо","свойство","долг","поколение","животное","схема","усилие","отличие","остров","противник","волна","реализация","страница","формирование","житель","красота","птица","растение","тень","явление","храм","запах","водка","наличие","ужас","одежда","кресло","больной","поезд","университет","традиция","адрес","декабрь","ладонь","сведение","цветок","лидер","октябрь","занятие","сентябрь","помещение","январь","зритель","редакция","стиль","весна","фактор","август","известие","зависимость","охрана","оборудование","концерт","отделение","расход","выставка","милиция","переход","эпоха","запад","произведение","родина","собственность","тайна","трава","лагерь","имущество","кровать","аппарат","середина","март","клиент","дама","фронт","отрасль","стул","беседа","законодательство","продажа","повышение","музей","след","полковник","сомнение","понимание","апрель","князь","рыба","дума","кодекс","сутки","чудо","шея","судья","крыша","настроение","поток","должность","преступление","мозг","честь","пост","еврей","июнь","сотня","дождь","лестница","дача","установка","появление","получение","образец","труба","главное","осень","костюм","баба","ценность","обязанность","пьеса","таблица","вино","воспоминание","лошадь","коллега","организм","ученик","учреждение","открытие","том","черта","характеристика","выполнение","оборона","выступление","температура","перспектива","подруга","приказ","жертва","ресторан","километр","спор","вкус","признак","промышленность","американец","лоб","заключение","восток","исключение","ключ","постановление","слой","бок","июль","перевод","секретарь","кусок","слух","польза","звонок","обстановка","чиновник","соглашение","деталь","русский","тишина","зарплата","билет","подарок","тюрьма","ящик","конкурс","книжка","изучение","просьба","царь","публика","смех","сообщение","угроза","беда","блок","достижение","назначение","реклама","портрет","масло","стакан","урок","часы","крик","творчество","телевизор","инструмент","концепция","лейтенант","экран","дно","реальность","канал","мясо","знакомый","щека","конфликт","переговоры","запись","вагон","площадка","последствие","сотрудничество","зеркало","тон","академия","палата","потребность","ноябрь","увеличение","дурак","поездка","обед","потеря","февраль","мероприятие","парк","принятие","устройство","вещество","категория","сезон","гостиница","издание","объединение","темнота","человечество","колесо","опасность","разрешение","воздействие","коллектив","камера","запас","следствие","длина","крыло","округ","фон","кандидат","родственник","давление","присутствие","взаимодействие","доска","партнер","двигатель","шум","достоинство","грех","нож","полет","страсть","испытание","TRUE","оплата","разница","водитель","пакет","снижение","формула","живот","капитал","мост","новость","эффект","вход","губернатор","доклад","смена","убийство","эксперт","автобус","платье","кадр","тетя","общение","психология","лев","порог","проверка","процедура","рабочий","ремонт","обращение","обучение","ожидание","памятник","корень","наблюдение","буква","доказательство","признание","постель","штаб","владелец","компьютер","инженер","старуха","лодка","ракета","серия","шутка","вершина","выпуск","кулак","лед","торговля","нефть","молодежь","цифра","корпус","недостаток","сапог","сущность","талант","эффективность","кофе","полоса","основное","рассмотрение","сбор","штат","следователь","жилье","мешок","описание","куст","отказ","замок","редактор","дворец","забота","пиво","диван","столик","эксперимент","печать","кольцо","пистолет","воспитание","начальство","профессия","ворота","добро","дружба","покой","риск","окончание","дым","брак","величина","записка","инициатива","совесть","активность","кость","спорт","кредит","господь","майор","конференция","потолок","библиотека","помощник","конструкция","отдых","ручка","металл","молоко","прокурор","транспорт","поэзия","соединение","краска","расстояние","мечта","село","еда","зло","подразделение","сюжет","рубеж","сигнал","атмосфера","крест","вес","взрыв","контакт","сигарета","восторг","золото","почва","премия","король","подъезд","шанс","автомат","заказ","мальчишка","очки","миг","штука","чтение","поселок","свидетель","ставка","сумка","удивление","хвост","песок","поворот","возвращение","мгновение","статус","озеро","строй","параметр","сказка","тенденция","вина","дыхание","версия","масштаб","монастырь","хозяйка","дочка","танец","эксплуатация","коммунист","пенсия","приятель","объяснение","набор","производитель","пыль","философия","мощность","обязательство","уход","горло","кризис","указание","плата","яблоко","препарат","действительность","москвич","остаток","изображение","сделка","сочинение","покупатель","танк","затрата","строка","единица","обработка","чемпионат"]
var movieData = ["The Shawshank Redemption",
	"The Godfather",
	"The Godfather, Part II",
	"The Dark Knight",
	"Pulp Fiction",
	"The Good, The Bad and The Ugly",
	"12 Angry Men",
	"Schindler's List",
	"The Lord of the Rings: The Return of the King",
	"Fight Club",
	"The Fellowship Of The Ring",
	"Star Wars: Episode V - The Empire Strikes Back",
	"Inception",
	"Forrest Gump",
	"One Flew Over the Cuckoo's Nest",
	"The Lord of the Rings: The Two Towers",
	"Interstellar",
	"Goodfellas",
	"The Matrix",
	"Star Wars: Episode IV - A New Hope",
	"Seven Samurai",
	"City of God",
	"Se7en",
	"The Usual Suspects",
	"The Silence of the Lambs",
	"It's a Wonderful Life",
	"Once Upon a Time in the West",
	"Leon: The Professional",
	"Life Is Beautiful",
	"Casablanca",
	"Raiders of the Lost Ark",
	"American History X",
	"Saving Private Ryan",
	"City Lights",
	"Psycho",
	"Spirited Away",
	"Rear Window",
	"Intouchables",
	"Modern Times",
	"Whiplash",
	"Terminator 2: Judgment Day",
	"Memento",
	"The Green Mile",
	"The Pianist",
	"The Departed",
	"Sunset Boulevard",
	"Apocalypse Now",
	"Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb",
	"Gladiator",
	"Back to the Future",
	"Alien",
	"The Prestige",
	"The Great Dictator",
	"The Lives of Others",
	"The Lion King",
	"Django Unchained",
	"The Dark Knight Rises",
	"Cinema Paradiso",
	"The Shining",
	"Paths of Glory",
	"American Beauty",
	"Wall-E",
	"North by Northwest",
	"Aliens",
	"Citizen Kane",
	"Vertigo",
	"Amelie",
	"M",
	"Das Boot",
	"Grave of the Fireflies",
	"Toy Story 3",
	"Oldboy",
	"Princess Mononoke",
	"Star Wars: Episode VI - Return of the Jedi",
	"Once Upon a Time in America",
	"A Clockwork Orange",
	"Reservoir Dogs",
	"Taxi Driver",
	"Double Indemnity",
	"Braveheart",
	"Requiem for a Dream",
	"To Kill a Mockingbird",
	"Lawrence of Arabia",
	"Witness for the Prosecution",
	"Eternal Sunshine of the Spotless Mind",
	"Full Metal Jacket",
	"Singin' in the Rain",
	"The Sting",
	"Bicycle Thieves",
	"Amadeus",
	"Monty Python and the Holy Grail",
	"Snatch",
	"Rashomon",
	"L.A. Confidential",
	"For a Few Dollars More",
	"2001: A Space Odyssey",
	"The Kid",
	"All About Eve",
	"The Apartment",
	"Some Like It Hot",
	"Inglourious Basterds",
	"Birdman",
	"Indiana Jones and the Last Crusade",
	"The Treasure of the Sierra Madre",
	"The Third Man",
	"A Seperation",
	"Yojimbo",
	"Toy Story",
	"Batman Begins",
	"Metropolis",
	"Like Stars on Earth",
	"Unforgiven",
	"Scarface",
	"Raging Bull",
	"Up",
	"Chinatown",
	"3 Idiots",
	"The Great Escape",
	"Downfall",
	"Boyhood",
	"Die Hard",
	"On the Waterfront",
	"Pan's Labyrinth",
	"Mr. Smith Goes to Washington",
	"The Hunt",
	"Heat",
	"CM101MMXI Fundamentals",
	"Gone Girl",
	"The Bridge on the River Kwai",
	"Good Will Hunting",
	"The Bandit",
	"My Neighbor Totoro",
	"The Seventh Seal",
	"Ikiru",
	"The Gold Rush",
	"The Elephant Man",
	"The Wolf of Wall Street",
	"Ran",
	"Wild Strawberries",
	"Blade Runner",
	"The General",
	"Lock, Stock and Two Smoking Barrels",
	"The Secret in Their Eyes",
	"Casino",
	"Gran Torino",
	"The Big Lebowski",
	"Warrior",
	"Rebecca",
	"V for Vendetta",
	"Howl's Moving Castle",
	"Paint It Yellow",
	"The Deer Hunter",
	"It Happened One Night",
	"Cool Hand Luke",
	"How to Train Your Dragon",
	"Fargo",
	"Judgment at Nuremberg",
	"Trainspotting",
	"Gone with the Wind",
	"Rush",
	"Into the Wild",
	"The Maltese Falcon",
	"A Beautiful Mind",
	"Dial M for Murder",
	"The Sixth Sense",
	"The Wages of Fear",
	"Hotel Rwanda",
	"The Thing",
	"Finding Nemo",
	"Mary and Max",
	"No Country for Old Men",
	"Butch Cassidy and the Sundance Kid",
	"Kill Bill: Vol. 1",
	"Platoon",
	"Life of Brian",
	"Incendies",
	"Guardians of the Galaxy",
	"Dil Chahta Hai",
	"12 Years a Slave",
	"Network",
	"Touch of Evil",
	"Diabolique (1955)",
	"Annie Hall",
	"The Princess Bride",
	"There Will Be Blood",
	"The Grand Budapest Hotel",
	"Stand by Me",
	"Sin City",
	"Ben-Hur",
	"The 400 Blows",
	"Amores Perros",
	"In the Name of the Father",
	"Million Dollar Baby",
	"The Grapes of Wrath",
	"The Wizard of Oz",
	"Hachi: A Dog's Tale",
	"Persona",
	"The Best Years of Our Lives",
	"The Avengers",
	"Nausicaä of the Valley of the Wind",
	"The Bourne Ultimatum",
	"Gandhi",
	"The Imitation Game",
	"Donnie Darko",
	"8 1/2",
	"Gangs of Wasseypur",
	"Strangers on a Train",
	"Infernal Affairs",
	"Stalker",
	"12 Monkeys",
	"Jaws",
	"Shutter Island",
	"X-Men: Days of Future Past",
	"High Noon",
	"Lagaan: Once Upon a Time in India",
	"Notorious",
	"The Terminator",
	"Before Sunrise",
	"The King's Speech",
	"Groundhog Day",
	"Harry Potter and the Deathly Hallows: Part 2",
	"Fanny and Alexander",
	"Ip Man",
	"The Battle of Algiers",
	"Rocky",
	"Dog Day Afternoon",
	"The Night of the Hunter",
	"Monsters, Inc.",
	"La Haine",
	"Memories of Murder",
	"La Strada",
	"Pirates of the Caribbean: The Curse of the Black Pearl",
	"Who's Afraid of Virginia Woolf?",
	"Barry Lyndon",
	"A Fistful of Dollars",
	"Castle in the Sky",
	"The Truman Show",
	"The Big Sleep",
	"The Help",
	"Jurassic Park",
	"Roman Holiday",
	"The Graduate",
	"The Hustler",
	"Papillon",
	"Beauty and the Beast",
	"In the Mood for Love",
	"The Celebration",
	"Prisoners",
	"Rope",
	"Swades: We, the People"
];

var defaultData = [
	"Africa",
	"Agent",
	"Air",
	"Alien",
	"Alps",
	"Amazon",
	"Ambulance",
	"America",
	"Angel",
	"Antarctica",
	"Apple",
	"Arm",
	"Atlantis",
	"Australia",
	"Aztec",
	"Back",
	"Ball",
	"Band",
	"Bank",
	"Bar",
	"Bark",
	"Bat",
	"Battery",
	"Beach",
	"Bear",
	"Beat",
	"Bed",
	"Beijing",
	"Bell",
	"Belt",
	"Berlin",
	"Bermuda",
	"Berry",
	"Bill",
	"Block",
	"Board",
	"Bolt",
	"Bomb",
	"Bond",
	"Boom",
	"Boot",
	"Bottle",
	"Bow",
	"Box",
	"Bridge",
	"Brush",
	"Buck",
	"Buffalo",
	"Bug",
	"Bugle",
	"Button",
	"Calf",
	"Canada",
	"Cap",
	"Capital",
	"Car",
	"Card",
	"Carrot",
	"Casino",
	"Cast",
	"Cat",
	"Cell",
	"Centaur",
	"Center",
	"Chair",
	"Change",
	"Charge",
	"Check",
	"Chest",
	"Chick",
	"China",
	"Chocolate",
	"Church",
	"Circle",
	"Cliff",
	"Cloak",
	"Club",
	"Code",
	"Cold",
	"Comic",
	"Compound",
	"Concert",
	"Conductor",
	"Contract",
	"Cook",
	"Copper",
	"Cotton",
	"Court",
	"Cover",
	"Crane",
	"Crash",
	"Cricket",
	"Cross",
	"Crown",
	"Cycle",
	"Czech",
	"Dance",
	"Date",
	"Day",
	"Death",
	"Deck",
	"Degree",
	"Diamond",
	"Dice",
	"Dinosaur",
	"Disease",
	"Doctor",
	"Dog",
	"Draft",
	"Dragon",
	"Dress",
	"Drill",
	"Drop",
	"Duck",
	"Dwarf",
	"Eagle",
	"Egypt",
	"Embassy",
	"Engine",
	"England",
	"Europe",
	"Eye",
	"Face",
	"Fair",
	"Fall",
	"Fan",
	"Fence",
	"Field",
	"Fighter",
	"Figure",
	"File",
	"Film",
	"Fire",
	"Fish",
	"Flute",
	"Fly",
	"Foot",
	"Force",
	"Forest",
	"Fork",
	"France",
	"Game",
	"Gas",
	"Genius",
	"Germany",
	"Ghost",
	"Giant",
	"Glass",
	"Glove",
	"Gold",
	"Grace",
	"Grass",
	"Greece",
	"Green",
	"Ground",
	"Ham",
	"Hand",
	"Hawk",
	"Head",
	"Heart",
	"Helicopter",
	"Himalayas",
	"Hole",
	"Hollywood",
	"Honey",
	"Hood",
	"Hook",
	"Horn",
	"Horse",
	"Horseshoe",
	"Hospital",
	"Hotel",
	"Ice",
	"Ice Cream",
	"India",
	"Iron",
	"Ivory",
	"Jack",
	"Jam",
	"Jet",
	"Jupiter",
	"Kangaroo",
	"Ketchup",
	"Key",
	"Kid",
	"King",
	"Kiwi",
	"Knife",
	"Knight",
	"Lab",
	"Lap",
	"Laser",
	"Lawyer",
	"Lead",
	"Lemon",
	"Leprechaun",
	"Life",
	"Light",
	"Limousine",
	"Line",
	"Link",
	"Lion",
	"Litter",
	"Loch Ness",
	"Lock",
	"Log",
	"London",
	"Luck",
	"Mail",
	"Mammoth",
	"Maple",
	"Marble",
	"March",
	"Mass",
	"Match",
	"Mercury",
	"Mexico",
	"Microscope",
	"Millionaire",
	"Mine",
	"Mint",
	"Missile",
	"Model",
	"Mole",
	"Moon",
	"Moscow",
	"Mount",
	"Mouse",
	"Mouth",
	"Mug",
	"Nail",
	"Needle",
	"Net",
	"New York",
	"Night",
	"Ninja",
	"Note",
	"Novel",
	"Nurse",
	"Nut",
	"Octopus",
	"Oil",
	"Olive",
	"Olympus",
	"Opera",
	"Orange",
	"Organ",
	"Palm",
	"Pan",
	"Pants",
	"Paper",
	"Parachute",
	"Park",
	"Part",
	"Pass",
	"Paste",
	"Penguin",
	"Phoenix",
	"Piano",
	"Pie",
	"Pilot",
	"Pin",
	"Pipe",
	"Pirate",
	"Pistol",
	"Pit",
	"Pitch",
	"Plane",
	"Plastic",
	"Plate",
	"Platypus",
	"Play",
	"Plot",
	"Point",
	"Poison",
	"Pole",
	"Police",
	"Pool",
	"Port",
	"Post",
	"Pound",
	"Press",
	"Princess",
	"Pumpkin",
	"Pupil",
	"Pyramid",
	"Queen",
	"Rabbit",
	"Racket",
	"Ray",
	"Revolution",
	"Ring",
	"Robin",
	"Robot",
	"Rock",
	"Rome",
	"Root",
	"Rose",
	"Roulette",
	"Round",
	"Row",
	"Ruler",
	"Satellite",
	"Saturn",
	"Scale",
	"School",
	"Scientist",
	"Scorpion",
	"Screen",
	"Scuba Diver",
	"Seal",
	"Server",
	"Shadow",
	"Shakespeare",
	"Shark",
	"Ship",
	"Shoe",
	"Shop",
	"Shot",
	"Sink",
	"Skyscraper",
	"Slip",
	"Slug",
	"Smuggler",
	"Snow",
	"Snowman",
	"Sock",
	"Soldier",
	"Soul",
	"Sound",
	"Space",
	"Spell",
	"Spider",
	"Spike",
	"Spine",
	"Spot",
	"Spring",
	"Spy",
	"Square",
	"Stadium",
	"Staff",
	"Star",
	"State",
	"Stick",
	"Stock",
	"Straw",
	"Stream",
	"Strike",
	"String",
	"Sub",
	"Suit",
	"Superhero",
	"Swing",
	"Switch",
	"Table",
	"Tablet",
	"Tag",
	"Tail",
	"Tap",
	"Teacher",
	"Telescope",
	"Temple",
	"Theater",
	"Thief",
	"Thumb",
	"Tick",
	"Tie",
	"Time",
	"Tokyo",
	"Tooth",
	"Torch",
	"Tower",
	"Track",
	"Train",
	"Triangle",
	"Trip",
	"Trunk",
	"Tube",
	"Turkey",
	"Undertaker",
	"Unicorn",
	"Vacuum",
	"Van",
	"Vet",
	"Wake",
	"Wall",
	"War",
	"Washer",
	"Washington",
	"Watch",
	"Water",
	"Wave",
	"Web",
	"Well",
	"Whale",
	"Whip",
	"Wind",
	"Witch",
	"Worm",
	"Yard"
];

var spanishData = [
	"Aguila",
	"Aguja",
	"Agujero",
	"Aire",
	"Alemania",
	"Algodun",
	"Alianza",
	"Alpes",
	"Ambulancia",
	"America",
	"Angel",
	"Anillo",
	"Antartida",
	"Antorcha",
	"Araoa",
	"Archivo",
	"Arco",
	"Argentina",
	"Articulo",
	"As",
	"Atlantida",
	"Azteca",
	"Baile",
	"Bala",
	"Ballena",
	"Banco",
	"Banda",
	"Baoo",
	"Barco",
	"Barra",
	"Bateria",
	"Berlin",
	"Bermudas",
	"Bicho",
	"Blanco",
	"Bloque",
	"Boca",
	"Bola",
	"Bolsa",
	"Bomba",
	"Bosque",
	"Bota",
	"Botella",
	"Botun",
	"Brazo",
	"Bruja",
	"Caballero",
	"Caballo",
	"Cabeza",
	"Cabina",
	"Cabo",
	"Cactus",
	"Cadena",
	"Caja",
	"Cama",
	"Camara",
	"Cambio",
	"Campana",
	"Campo",
	"Canal",
	"Canguro",
	"Canto",
	"Caoa",
	"Capa",
	"Capital",
	"Caqui",
	"Cara",
	"Caravana",
	"Carga",
	"Carrera",
	"Carro",
	"Carta",
	"Casco",
	"Casino",
	"Caza",
	"Cementerio",
	"Centauro",
	"Centro",
	"Cervantes",
	"Checo",
	"Chocolate",
	"Choque",
	"Chuleta",
	"Cientifico",
	"Cinta",
	"Cinturun",
	"Circulo",
	"Clase",
	"Coche",
	"Cocinero",
	"Coco",
	"Cudigo",
	"Cola",
	"Culera",
	"Columna",
	"Cometa",
	"Compas",
	"Concierto",
	"Conejo",
	"Contrabandista",
	"Copa",
	"Corazun",
	"Corneta",
	"Corona",
	"Corredor",
	"Corriente",
	"Corte",
	"Cresta",
	"Cromo",
	"Cruz",
	"Cuadro",
	"Cuarto",
	"Cubierta",
	"Cubo",
	"Cuchillo",
	"Cuello",
	"Cuerda",
	"Cuerno",
	"Cura",
	"Dama",
	"Delta",
	"Destino",
	"Dia",
	"Diamante",
	"Diana",
	"Diario",
	"Diente",
	"Dinosaurio",
	"Disco",
	"Don",
	"Dragun",
	"Duende",
	"Egipto",
	"Embajada",
	"Emperador",
	"Enano",
	"Enfermedad",
	"Enfermera",
	"Enlace",
	"Escorpiun",
	"Espacio",
	"Espia",
	"Estaciun",
	"Estadio",
	"Estado",
	"Estrella",
	"Estudio",
	"Etiqueta",
	"Europa",
	"Extraterrestre",
	"Falda",
	"Fantasma",
	"Faro",
	"Ficha",
	"Fiesta",
	"Figura",
	"Flauta",
	"Flecha",
	"Foso",
	"Francia",
	"Frente",
	"Fuego",
	"Fuente",
	"Fuerza",
	"Furgoneta",
	"Gancho",
	"Gato",
	"Genio",
	"Gigante",
	"Golfo",
	"Golondrina",
	"Golpe",
	"Goma",
	"Gundola",
	"Gota",
	"Grado",
	"Granada",
	"Grano",
	"Grecia",
	"Grifo",
	"Guante",
	"Guardia",
	"Guerra",
	"Gusano",
	"Helado",
	"Helicuptero",
	"Hielo",
	"Hierba",
	"Hoja",
	"Hollywood",
	"Horca",
	"Hospital",
	"Hotel",
	"Iglesia",
	"Iman",
	"India",
	"Indice",
	"Inglaterra",
	"Italia",
	"Jarra",
	"Judia",
	"Juicio",
	"Kiwi",
	"Ladrun",
	"Lago Ness",
	"Laser",
	"Latigo",
	"Lengua",
	"Leun",
	"Libra",
	"Lima",
	"Limusina",
	"Linea",
	"Lista",
	"Llama",
	"Llave",
	"Lomo",
	"Londres",
	"Luna",
	"Luz",
	"Maestro",
	"Magia",
	"Malta",
	"Mancha",
	"Mando",
	"Manga",
	"Mango",
	"Mano",
	"Manzana",
	"Maoana",
	"Marca",
	"Marcha",
	"Marfil",
	"Masa",
	"Mascara",
	"Mazo",
	"Medico",
	"Mercurio",
	"Mesa",
	"Metro",
	"Mexico",
	"Micro",
	"Microscopio",
	"Mielo",
	"Millonario",
	"Mina",
	"Misil",
	"Modelo",
	"Mudulo",
	"Monitor",
	"Mono",
	"Mortero",
	"Mosc˙",
	"Motor",
	"Muelle",
	"Muerte",
	"Muoeca",
	"Muro",
	"Naranja",
	"Nave",
	"Nieve",
	"Nilo",
	"Ninja",
	"Noche",
	"Nota",
	"Nudo",
	"Nueva York",
	"Obra",
	"Ojo",
	"Ola",
	"Olimpo",
	"Upera",
	"Orden",
	"Urgano",
	"Ornitorrinco",
	"Oro",
	"Oso",
	"Pala",
	"Palma",
	"Pantalla",
	"Papel",
	"Paracaidas",
	"Pase",
	"Paso",
	"Pasta",
	"Pastel",
	"Pavo",
	"Pekin",
	"Pelicula",
	"Pelotun",
	"Pendiente",
	"Perro",
	"Pez",
	"Pico",
	"Pie",
	"Pieza",
	"Pila",
	"Piloto",
	"Pincho",
	"Ping¸ino",
	"Pinta",
	"Pioa",
	"Piramide",
	"Pirata",
	"Pista",
	"Pistola",
	"Placa",
	"Plano",
	"Planta",
	"Platano",
	"Playa",
	"Plomo",
	"Pluma",
	"Policia",
	"Polo",
	"Portada",
	"Portero",
	"Potro",
	"Prensa",
	"Prima",
	"Princesa",
	"Puente",
	"Puerto",
	"Pulpo",
	"Pulso",
	"Punta",
	"Punto",
	"Radio",
	"Rascacielos",
	"Ratun",
	"Rayo",
	"Red",
	"Regla",
	"Reina",
	"Reserva",
	"Revoluciun",
	"Rey",
	"Robot",
	"Rojo",
	"Roma",
	"Ronda",
	"Rosa",
	"Ruleta",
	"Sable",
	"Sa"
];
